# Set terminal to support 256 colors
set -g default-terminal "xterm-256color"

set -g mouse on

# Fix garbage characters on attach (increase escape time)
# set -sg escape-time 500

# Alternative: If you use mouse mode, turn off focus-events
# set -g focus-events off
