# Enable mouse support for scrolling, selecting, and resizing
set -g mouse on

# Start window and pane numbering at 1 (more intuitive)
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Enable true color support
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
